package co.edu.uco.arquisw.dominio.transversal.enumerator;

public enum TipoNotificacion {
    GENERAL,
    ACTIVACION_CUENTA_INICIADA,
    ASOCIACION_ELIMINADA,
    ASOCIACION_ELIMINADA_POR_ADMINISTRADOR,
    CONTRATO_ACTUALIZADO,
    CONTRATO_GUARDADO,
    NECESIDAD_ELIMINADA,
    NECESIDAD_ELIMINADA_POR_ADMINISTRADOR,
    PERSONA_ELIMINADA,
    PERSONA_ELIMINADA_POR_ADMINISTRADOR,
    PROYECTO_APROBADO,
    PROYECTO_APROBADO_POR_ROL_DIRECTOR_DE_PROYECTO,
    PROYECTO_APROBADO_POR_ROL_INGENIERIA,
    PROYECTO_APROBADO_POR_LIDER_DE_EQUIPO,
    PROYECTO_RECHAZADO,
    RECUPERACION_CLAVE_INICIADA,
    USUARIO_RECHAZADO,
    USUARIO_SELECCIONADO
}
